### ISSUE TITLE
Make Syntax Tree Visualizer part of VSHaxe ?

### ISSUE THREAD

**Issue by melMass** [vshaxe/vshaxe-debug-tools#12]
Hi,

I just discovered this extension, the Syntax Tree Visualizer is actually very useful for many things, macros, for instance, I might be wrong but I think it should be part of the core vshaxe extension for that reason, don't you think?

**Comment by Gama11** [comment]
This doesn't visualize Haxe's AST, it visualizes the token tree, so it's not very useful for macros. But yeah, if we did have a visualizer for Haxe AST, that would be useful to have in vshaxe.

**Comment by melMass** [comment]
Yes I just realised that.
Do you know a way to visualize haxe's AST, I'm building quite complex macros and for now I use tink_macro and a few functions to debug them, I learned a lot using that workflow and it's working but it's pretty slow to debug...

**Comment by Gama11** [comment]
Have you tried eval-debugger? It doesn't exactly "visualize" the AST, but it still prints expressions in a nice readable fashion: https://github.com/HaxeFoundation/haxe/issues/7860

**Comment by melMass** [comment]
Whaaatt ??? That's way better than my messed up solution, how do you enable it?

**Comment by Gama11** [comment]
There's not much to it: https://github.com/vshaxe/vshaxe/wiki/Debugging

**Comment by melMass** [comment]
Thanks I'll look into it as soon as I have the time.
